# Generated by Django 2.2.9 on 2020-01-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='jhhkh',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
